title: kix
description: Talks & Ramblings
url: https://www.kix.in
author:
  name: Anant Narayanan
social:
  name: Anant Narayanan
  links:
    - https://twitter.com/anantn
    - https://www.facebook.com/anantn
    - https://www.linkedin.com/in/anantn
    - https://github.com/anantn
    - https://keybase.io/anant
logo: /favicon.ico
permalink: :year/:month/:day/:title/
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
collections:
  - orgs
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext
include:
  - _pages
sass:
  style: compressed
