name: Binary Sunrise
description: Assorted ramblings of your next-door hacker
url: http://kix.in
author: Anant Narayanan
permalink: :year/:month/:day/:title/
markdown: rdiscount
rdiscount:
  extensions: [smart]